[metadata]
name = shape_retrieval
author = Grisell Diaz Leines
author_email = gdiazleines@ebi.ac.uk
description = This python package calculates surface shape descriptors for macromolecular assemblies and interfaces, and computes shape similarity scores.
version = 2.0.0
url = https://github.com/PDBe-KB/pdbe_shape-retrieval
keywords =
  interfaces assemblies pisa json 
classifiers =
  Development Status :: 4 - Beta
  Intended Audience :: Life Science/Structural Biology
  Intended Audience :: Developers
  Programming Language :: Python :: 3.10
  Programming Language :: Python :: 3.11
  Programming Language :: Python :: 3.12
long_description = file: README.md
long_description_content_type = text/markdown
license_files =
  LICENSE

[options]
python_requires = >= 3.10
packages = find_namespace:
zip_safe: False
include_package_data = True
install_requires =
  imageio
  ipywidgets
  lxml>=4.6.3,<5.0.0
  matplotlib
  numpy
  pandas
  potpourri3d
  pydantic
  pyfmaps
  pyglet
  pymeshlab
  pymeshfix
  pythreejs
  requests
  robust_laplacian
  scikit-learn
  scipy
  seaborn
  torch
  tqdm
  trimesh

[options.extras_require]
test =
  pytest
  pytest-cov
  pytest-mock
dev =
  build
  pre-commit
  pytest
  pytest-cov
  pytest-mock
  twine

[options.entry_points]
console_scripts = 
  shape_retrieval = shape_utils.cli:main
